const KEY = 'eventAlarmShowcase';
const sample = { events: [{ id: 'sample-1', title: 'File Taxes', type: 'Finance', date: '2027-04-15', details: 'Prepare tax documents and submit the annual return.' }], alarms: [{ id: 'alarm-1', eventId: 'sample-1', date: '2027-04-01', delivery: 'Email', status: 'Scheduled' }] };
const load = () => JSON.parse(localStorage.getItem(KEY) || 'null') || structuredClone(sample);
const save = value => localStorage.setItem(KEY, JSON.stringify(value));
const clean = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const notice = (text, error = false) => { const el = document.querySelector('#message'); if (el) el.innerHTML = `<p class="status ${error ? 'error' : ''}">${clean(text)}</p>`; };
const query = new URLSearchParams(location.search); const data = load();

function eventCard(event) { const alarm = data.alarms.find(item => item.eventId === event.id); return `<article class="card"><h2>${clean(event.title)}</h2><p><strong>${clean(event.type)}</strong> — ${clean(event.date)}</p><p>${clean(event.details)}</p><p>Alarm: <strong>${alarm ? clean(alarm.status) : 'Not set'}</strong></p><div class="actions"><a class="button" href="event-form.html?id=${encodeURIComponent(event.id)}">Update</a><button class="danger delete-event" data-id="${clean(event.id)}">Delete</button><a class="button secondary" href="index.html">Cancel</a></div></article>`; }
function initDashboard() { const next = [...data.events].sort((a, b) => a.date.localeCompare(b.date))[0]; document.querySelector('#next-event').innerHTML = next ? eventCard(next) : '<p>No events scheduled. Choose New Event to begin.</p>'; }

function initEventForm() {
  const form = document.querySelector('#event-form'); const id = query.get('id'); const existing = data.events.find(event => event.id === id); const alarm = data.alarms.find(item => item.eventId === id);
  const templates = { passport: { title: 'Passport Renewal', type: 'Government', details: 'Gather the required documents, take a passport photo, and submit the renewal application.' }, taxes: { title: 'File Taxes', type: 'Finance', details: 'Collect income and deduction documents, review the return, and submit it before the deadline.' } };
  if (existing) { ['title', 'type', 'date', 'details'].forEach(field => document.querySelector(`#${field}`).value = existing[field]); document.querySelector('#event-id').value = id; document.querySelector('#delete-event').hidden = false; document.querySelector('#alarm-settings').href = `alarm-form.html?eventId=${encodeURIComponent(id)}`; document.querySelector('#alarm-settings').hidden = false; }
  if (alarm) { document.querySelector('#set-alarm').value = 'yes'; document.querySelector('#alarm-summary').textContent = `${alarm.status}: ${alarm.date} by ${alarm.delivery}`; }
  document.querySelector('#template').addEventListener('change', event => { const template = templates[event.target.value]; if (!template) return; Object.entries(template).forEach(([field, value]) => document.querySelector(`#${field}`).value = value); notice(`${template.title} template applied. Choose a date and review the details.`); });
  form.addEventListener('submit', event => { event.preventDefault(); if (!form.checkValidity()) return form.reportValidity(); const eventId = id || crypto.randomUUID(); const record = { id: eventId, title: document.querySelector('#title').value.trim(), type: document.querySelector('#type').value, date: document.querySelector('#date').value, details: document.querySelector('#details').value.trim() }; const index = data.events.findIndex(item => item.id === eventId); if (index >= 0) data.events[index] = record; else data.events.push(record); if (document.querySelector('#set-alarm').value === 'no') data.alarms = data.alarms.filter(item => item.eventId !== eventId); save(data); location.href = document.querySelector('#set-alarm').value === 'yes' ? `alarm-form.html?eventId=${encodeURIComponent(eventId)}` : 'events.html?saved=1'; });
  document.querySelector('#delete-event').addEventListener('click', () => deleteEvent(id));
}

function initAlarmForm() {
  const eventId = query.get('eventId'); const event = data.events.find(item => item.id === eventId); if (!event) { notice('Choose or save an event before creating an alarm.', true); document.querySelector('#alarm-form').hidden = true; return; }
  const alarm = data.alarms.find(item => item.eventId === eventId); document.querySelector('#alarm-event-title').textContent = `Reminder for ${event.title}`; document.querySelector('#cancel-alarm').href = `event-form.html?id=${encodeURIComponent(eventId)}`;
  if (alarm) { document.querySelector('#alarm-id').value = alarm.id; document.querySelector('#alarm-date').value = alarm.date; document.querySelector('#delivery').value = alarm.delivery; document.querySelector('#delete-alarm').hidden = false; }
  document.querySelector('#alarm-form').addEventListener('submit', formEvent => { formEvent.preventDefault(); const form = formEvent.currentTarget; if (!form.checkValidity()) return form.reportValidity(); const dateField = document.querySelector('#alarm-date'); if (dateField.value > event.date) { dateField.setCustomValidity('Alarm date cannot be after the event date.'); form.reportValidity(); dateField.setCustomValidity(''); return; } data.alarms = data.alarms.filter(item => item.eventId !== eventId); data.alarms.push({ id: alarm?.id || crypto.randomUUID(), eventId, date: dateField.value, delivery: document.querySelector('#delivery').value, status: 'Scheduled' }); save(data); location.href = 'alarms.html?saved=1'; });
  document.querySelector('#delete-alarm').addEventListener('click', () => { if (!confirm('Delete this alarm?')) return; data.alarms = data.alarms.filter(item => item.eventId !== eventId); save(data); location.href = 'alarms.html?deleted=1'; });
}

function deleteEvent(id) { if (!confirm('Delete this event and its alarm? This cannot be undone.')) return; data.events = data.events.filter(event => event.id !== id); data.alarms = data.alarms.filter(alarm => alarm.eventId !== id); save(data); location.href = 'events.html?deleted=1'; }
function initEvents() { if (query.has('saved')) notice('Event saved successfully.'); if (query.has('deleted')) notice('Event deleted.'); const list = document.querySelector('#event-list'); list.innerHTML = data.events.length ? data.events.map(eventCard).join('') : '<div class="card"><p>No saved events.</p></div>'; list.addEventListener('click', event => { if (event.target.matches('.delete-event')) deleteEvent(event.target.dataset.id); }); }
function initAlarms() { if (query.has('saved')) notice('Alarm saved successfully.'); if (query.has('deleted')) notice('Alarm deleted.'); const list = document.querySelector('#alarm-list'); list.innerHTML = data.alarms.length ? data.alarms.map(alarm => { const event = data.events.find(item => item.id === alarm.eventId); return `<article class="card"><h2>${clean(event?.title || 'Deleted event')}</h2><p>Alarm date: ${clean(alarm.date)}</p><p>Delivery: <strong>${clean(alarm.delivery)}</strong> (pseudo-delivery)</p><p>Status: <strong>${clean(alarm.status)}</strong></p><div class="actions"><a class="button" href="alarm-form.html?eventId=${encodeURIComponent(alarm.eventId)}">Update</a><button class="danger delete-alarm" data-id="${clean(alarm.id)}">Delete</button><a class="button secondary" href="index.html">Cancel</a></div></article>`; }).join('') : '<div class="card"><p>No alarms scheduled.</p></div>'; list.addEventListener('click', event => { if (!event.target.matches('.delete-alarm') || !confirm('Delete this alarm?')) return; data.alarms = data.alarms.filter(item => item.id !== event.target.dataset.id); save(data); notice('Alarm deleted.'); initAlarms(); }); }

const page = document.body.dataset.page; ({ dashboard: initDashboard, 'event-form': initEventForm, 'alarm-form': initAlarmForm, events: initEvents, alarms: initAlarms }[page] || (() => {}))();
